### ISSUE TITLE
sgblockgiveawaybutton.user.js - Doesn't work with long names

### ISSUE THREAD

**Issue by InvictusX** [Daerphen/sgscripts#1]
- [x] Button does not add games to filter if the game has some ridiculously long name which SG cuts off with "..." at the end. See example below.

Original Name | SG Display
---|---  
BANZAI PECAN: The Last Hope For the Young Century | BANZAI PECAN: The Last Hope For the Young Cen...

---

- [x] Also a minor issue: It's still 2 buttons if you use this script with [SG++](https://github.com/leomoty/SGPP).
![dublicate_btn](https://cloud.githubusercontent.com/assets/17688383/13763982/de1415ae-ea4a-11e5-921b-96a0aa18cadb.png)

**Comment by Daerphen** [comment]
Solved the minor issue with the duplicated buttons.

**Comment by Daerphen** [comment]
Can you test the script? The issue should be fixed with the latest push.
I am now parsing the game_id from a different source. Should work with the long titles.

**Comment by InvictusX** [comment]
Yep, it works perfectly fine now.
