### ISSUE TITLE
group giveaways hiding on groups own page

### ISSUE THREAD

**Issue by CaitSith2** [Daerphen/sgscripts#4]
It would be nice to be able to hide a given groups giveaways, unless I am browsing the groups own page.

for example,  I am a member of the grout Unlucky-7.  Its has some rules regarding which giveaways from the group I may, and may not enter.  I would like for the giveaways from that group to NOT show up on the front page,  but when I do go into the groups page,  I would like the GAs to show up there, irregardless of the hide setting for that group.

**Comment by Daerphen** [comment]
Actually there is already a script for that. But iirc it would hide the giveaways on the group page as well.

sggroupexcluder.user.js 
activate this and you can go to the group-list in your account settings. There you can activate/deactivate a group

sggroupidentifier.user.js
activate this script and groups that has been deactivated by the other script are now hidden.

Haven't tested it right now, let me know if there are issues
